### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by SmileyChris** [jchoca/fishbowl-api#2]
Hi James,

You might have noticed that I have a fork which hacked to death your initial code. I released it under an open MIT license but am realising since I still used your code as the base that I should check that you're fine with this.

Are you happy to add an MIT / BSD license to the project (or at least give permission for me to release my code which has remnants of your initial work under this license)?

Cheers!

**Comment by jchoca** [comment]
Hey Chris, sorry for my late reply. I've gone ahead and added the license.
