### ISSUE TITLE
Feature complete ?

### ISSUE THREAD

**Issue by beadon1** [jchoca/fishbowl-api#3]
This repo has not been modified for 5+ years.  Is this tool considered feature complete ?  Or is there a better API to use ?  Fishbowl continues to add releases and features, but it is unclear if this works with the latest releases.

**Comment by jchoca** [comment]
Hi @beadon-SAT, sorry I missed this somehow. This repo has not been maintained at all, so I would say "no." I also don't currently have access to Fishbowl anymore. This repo can probably serve as a starting point if you want to fork it though.
